---
name: ((deployment_name))

stemcells:
- alias: default
  os: ubuntu-jammy
  version: latest
releases:
  - name: defectdojo
    version: latest
  - name: bpm
    version: latest
  - name: routing
    version: latest
  - name: bosh-dns-aliases
    version: latest

update:
  canaries: 2
  max_in_flight: 1
  canary_watch_time: 5000-60000
  update_watch_time: 5000-60000
instance_groups:
- name: defectdojo
  azs: [z1, z2]
  instances: 1
  jobs:
    - name: bosh-dns-aliases
      properties:
        aliases:
        - domain: opsuaa.internal
          targets:
          - deployment: opsuaa
            domain: bosh
            instance_group: opsuaa
            network: opsuaa
            query: '*'
      release: bosh-dns-aliases
    - name: bpm
      release: bpm
    - name: godojo
      release: defectdojo
    - name: nginx_dojo
      release: defectdojo
      properties:
        nginx:
            server_name: ((nginx_server_name))
  vm_type: t3.medium
  stemcell: default
  persistent_disk: 10240
  networks:
    - name: ((defectdojo_network))
  vm_extensions:
    - ((defectdojo_extension))
