nginx_server_name: ((staging-nginx-server-name))
deployment_name: ((staging-deployment-name))
defectdojo_network: ((staging-defectdojo-network))
defectdojo_extension: ((staging-defectdojo-extension))
defectdojo_version: ((staging-defectdojo-version))
defectdojo_quiet: ((staging-defectdojo-quiet))
defectdojo_trace: ((staging-defectdojo-trace))
defectdojo_redact: ((staging-defectdojo-redact))
defectdojo_root: ((staging-defectdojo-root))
defectdojo_source: ((staging-defectdojo-source))
defectdojo_files: ((staging-defectdojo-files))
defectdojo_media: ((staging-defectdojo-media))
defectdojo_static: ((staging-defectdojo-static))
defectdojo_app: ((staging-defectdojo-app))
defectdojo_db_engine: ((staging-defectdojo-db-engine))
defectdojo_db_local: ((staging-defectdojo-db-local))
defectdojo_db_exists: ((staging-defectdojo-db-exists))
defectdojo_db_ruser: ((staging-defectdojo-db-ruser))
defectdojo_db_rpass: ((staging-defectdojo-db-rpass))
defectdojo_db_name: ((staging-defectdojo-db-name))
defectdojo_db_user: ((staging-defectdojo-db-user))
defectdojo_db_pass: ((staging-defectdojo-db-pass))
defectdojo_db_host: ((staging-defectdojo-db-host))
defectdojo_db_port: ((staging-defectdojo-db-port))
defectdojo_db_drop: ((staging-defectdojo-db-drop))
defectdojo_os_user: ((staging-defectdojo-os-user))
defectdojo_os_pass: ((staging-defectdojo-os-pass))
defectdojo_os_group: ((staging-defectdojo-os-group))
defectdojo_os_uid:  ((staging-defectdojo-os-uid))
defectdojo_os_gid: ((staging-defectdojo-os-gid))
defectdojo_admin_user: ((staging-defectdojo-admin-user))
defectdojo_admin_pass: ((staging-defectdojo-admin-pass))
defectdojo_csrf_trusted_origins: ((staging-defectdojo-csrf-trusted-origins))
defectdojo_auth_client: ((staging-defectdojo-auth-client))
defectdojo_auth_secret: ((staging-defectdojo-auth-secret))
defectdojo_auth_domain: ((staging-defectdojo-auth-domain))
defectdojo_site_url: ((staging-defectdojo-site-url))
defectdojo_oidc_username_key: ((staging-defectdojo-username-key))
defectdojo_oidc_id_key: ((staging-defectdojo-oidc-id-key))
defectdojo_oidc_whitelisted_domains: ((staging-defectdojo-whitelisted-domains))
defectdojo_oidc_token_issuer: ((staging-defectdojo-oidc-token-issuer))
defectdojo_oidc_access_token_url: ((staging-defectdojo-oidc-access-token-url))
defectdojo_oidc_authorization_url: ((staging-defectdojo-oidc-authorization-url))
defectdojo_oidc_userinfo_url: ((staging-defectdojo-oidc-userinfo-url))
defectdojo_oidc_jwks_uri: ((staging-defectdojo-oidc-jwks-uri))
